# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:

  catalogdb:
    image: mongo

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Catalog/Microservices.Catalog.API/Dockerfile
    ports:
      - 80