# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "8082:15672"

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Catalog/Microservices.Catalog.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDbSettings:ConnectionString=mongodb://catalogdb:27017"
      - "CatalogDbSettings:DatabaseName=CatalogDb"
      - "CatalogDbSettings:CollectionName=Products"
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: src/Basket/Microservices.Basket.API/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - basketdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:RedisConnection=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
      - "EventBus:UserName=guest"
      - "EventBus:Password=guest"
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
