# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Catalog/Microservices.Catalog.API/Dockerfile

  basket.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Basket/Microservices.Basket.API/Dockerfile
