# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  ordersdb:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Catalog/Microservices.Catalog.API/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: src/Basket/Microservices.Basket.API/Dockerfile

  orders.api:
    image: orders.api
    build:
      context: .
      dockerfile: src/Orders/API/Microservices.Orders.API/Dockerfile

  ocelot.gateway:
    image: ocelot.gateway
    build:
      context: .
      dockerfile: src/ApiGateway/Microservices.Ocelot.ApiGateway/Dockerfile
