# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  ordersdb:
    container_name: ordersdb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "8082:15672"

  catalog.api:
    container_name: catalogapi
    ports:
      - "8080:80"
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDbSettings:ConnectionString=mongodb://catalogdb:27017"
      - "CatalogDbSettings:DatabaseName=CatalogDb"
      - "CatalogDbSettings:CollectionName=Products"
      - ASPNETCORE_URLS=http://+:80

  basket.api:
    container_name: basketapi
    ports:
      - "8081:80"
    depends_on:
      - basketdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:RedisConnection=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
      - "EventBus:UserName=guest"
      - "EventBus:Password=guest"
      - ASPNETCORE_URLS=http://+:80

  orders.api:
    container_name: ordersapi
    restart: on-failure
    ports:
      - "8083:80"
    depends_on:
      - ordersdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrdersConnection=Server=ordersdb;Database=OrdersDb;User Id=sa;Password=SwN12345678"
      - "EventBus:HostName=rabbitmq"
      - "EventBus:UserName=guest"
      - "EventBus:Password=guest"
      - ASPNETCORE_URLS=http://+:80

  ocelot.gateway:
    container_name: ocelotgateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - orders.api
    ports:
      - "8878:80"
